# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

- repo: local
  hooks:
  - id: autoflake
    name: "autoflake: reformat unused imports and variables"
    entry: autoflake
    files: contrall
    language: python
    args: [--remove-all-unused-imports, --in-place]
  - id: isort
    name: "isort: reformat imports (order and remove duplicated imports)"
    language: python
    files: contrall
    entry: isort
    stages: [commit]
    args: [--cr setup.cfg]
    
  - id: black
    name: "black: reformat python code (max line length, syntax, double quotes, etc)"
    files: contrall
    entry: black
    language: python

  - id: flake8
    name: "flake8: check python code"
    stages: [commit]
    files: contrall
    language: system
    entry: flake8 --config setup.cfg
